apiVersion: 1

datasources:
  - name: pgsql
    type: postgres
    url: $PGHOST:$PGPORT
    user: $PGUSER
    database: $PGDATABASE
    secureJsonData:
      password: $PGPASSWORD
    jsonData:
      sslmode: $PGSSLMODE
